# Generated by Django 2.2.5 on 2019-10-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentType', models.CharField(max_length=200)),
                ('NumberOfItems', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
