# Generated by Django 2.2.5 on 2019-10-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalworld', '0002_auto_20191007_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='medequipment',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
    ]
